// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rsk.AspNetCore.Fido.EntityFramework;

#nullable disable

namespace Migrations.Migrations.Fido
{
    [DbContext(typeof(FidoDbContext))]
    partial class FidoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rsk.AspNetCore.Fido.EntityFramework.Entities.FidoKey", b =>
                {
                    b.Property<string>("CredentialId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Algorithm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AttestationType")
                        .HasColumnType("int");

                    b.Property<string>("AuthenticatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AuthenticatorIdType")
                        .HasColumnType("int");

                    b.Property<int>("Counter")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CredentialAsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayFriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUsed")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserHandle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("FidoKeys", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
